### ISSUE TITLE
2d20-L not working

### ISSUE THREAD

**Issue by cairnswm** [aLittleTooQuiet/dice-utils#18]
The -L option does not seem to work with dice greater than 9

example ( 3d9 working correctly)
3d9-L
{ results: [ 6, 4, 8], total: 14 }

(3d20 incorrect)
3d20-L
{ results: [ 15, 2, 9 ], total: 46 }

**Comment by cairnswm** [comment]
May be any modifications to the base die as
1d20+5 = 35
{ results: [ 15], total: 35 }

**Comment by cairnswm** [comment]
Bit of playing with the regex in parse-die-notation suggests the regex should be
/[+\\-xX*><]{1}[\dL]*/

the 
+-x

means + to x not +,-,x

**Comment by aLittleTooQuiet** [comment]
Good catch! Thanks for filing a report.

**Comment by cairnswm** [comment]
@aLittleTooQuiet  thanks for update, but the 3d20-L still not working :(

**Comment by cairnswm** [comment]
Thanks!

Works fine Locally but I still get wierd stuff happening on Repl.it

Here is my script:

const diceUtils = require('dice-utils');
const { roll } = diceUtils;

let res = roll("2d20+1")
console.log("2d20+1", res)

res = roll("3d20L")
console.log("3d20L", res)

res = roll("3d20-L")
console.log("3d20-L", res)

res = roll("3d6-L")
console.log("3d6-L", res)

**Comment by aLittleTooQuiet** [comment]
Whoops. I forgot to build before publishing. v1.3.5 should work correctly.

**Comment by cairnswm** [comment]
Working now, thank you :)
